### ISSUE TITLE
Problems in .less style checking

### ISSUE THREAD

**Issue by EvsChen** [l5oo00/vscode-fecs-plugin#10]
![image](https://user-images.githubusercontent.com/20365185/41074706-f0a9d6fe-6a3b-11e8-9e6b-faf47ac4de4e.png)
如上图所示，问题应该是上一行有trilling space，然而报出的错误是
![image](https://user-images.githubusercontent.com/20365185/41074683-cd05bbb4-6a3b-11e8-9b55-c2dedf20aa67.png)

使用的是默认的fecs配置

**Comment by l5oo00** [comment]
这个插件只是直接调用 fecs 来做的检查， 建议去 [fecs](https://github.com/ecomfe/fecs) 或 [lesslint](https://github.com/ecomfe/node-lesslint) 去提 issue。
