### ISSUE TITLE
The keyword 'import' is reserved

### ISSUE THREAD

**Issue by wz57c** [l5oo00/vscode-fecs-plugin#12]
JS998: [强制] 存在兼容性问题或运行时错误。（Parsing error: The keyword 'import' is reserved）
现行版本： v1.0.0

还原到之前的版本是没有问题的

**Comment by l5oo00** [comment]
新版本基本都是基于你自己的 .fecsrc 或 .eslintrc 文件的， 方便提供下你的配置看看么

**Comment by wz57c** [comment]
我本地没有自己配置的这两个文件，未更新时是可以正常显示错误提示的，更新后就不行了

**Comment by l5oo00** [comment]
问题已经修复， 可以更新到 `1.0.1` 试试~
