### ISSUE TITLE
自闭合组件的问题

### ISSUE THREAD

**Issue by tsingwong** [l5oo00/vscode-fecs-plugin#14]
如 .vue/.san/.atom 等文件中，大多推荐是用自闭合组件

但是这样使用就会违反 fecs 规范中的 [强制-对-html5-中规定允许省略的闭合标签不允许省略闭合标签](https://github.com/ecomfe/spec/blob/master/html-style-guide.md#%E5%BC%BA%E5%88%B6-%E5%AF%B9-html5-%E4%B8%AD%E8%A7%84%E5%AE%9A%E5%85%81%E8%AE%B8%E7%9C%81%E7%95%A5%E7%9A%84%E9%97%AD%E5%90%88%E6%A0%87%E7%AD%BE%E4%B8%8D%E5%85%81%E8%AE%B8%E7%9C%81%E7%95%A5%E9%97%AD%E5%90%88%E6%A0%87%E7%AD%BE)

请问大佬这种情况应该协调呀？

下图是一个 类 .atom 文件

![image](https://user-images.githubusercontent.com/16622888/42306024-fa703c2a-805f-11e8-8aa1-6e8a5ea56e45.png)

**Comment by l5oo00** [comment]
那就听  规范的， 改为 不自闭合

实在不想改， 就加个 禁用的注释 `<!-- htmlcs-disable tag-pair -->` 试试

如果想让插件自动区分的话， 那得去升级 fecs 了
