### ISSUE TITLE
怎么支持后缀是.tpl的文件

### ISSUE THREAD

**Issue by ghost** [l5oo00/vscode-fecs-plugin#15]
怎么支持后缀是.tpl的文件

**Comment by l5oo00** [comment]
可以试试这几个配置：

- `vscode-fecs-plugin.jsLikeExt`: Specified 'js like' files extension that can use fecs.
- `vscode-fecs-plugin.cssLikeExt`: Specified 'css like' files extension that can use fecs.
- `vscode-fecs-plugin.htmlLikeExt`: Specified 'html like' files extension that can use fecs.
- `vscode-fecs-plugin.vueLikeExt`: Specified 'vue like' files extension that can use fecs.
