### ISSUE TITLE
不支持.vue 结尾的文件

### ISSUE THREAD

**Issue by Hooper93** [l5oo00/vscode-fecs-plugin#16]
![image](https://user-images.githubusercontent.com/48215196/95644510-b4170f80-0ae9-11eb-9325-9e7d1fb2d5ce.png)
如图，双引号，缩进等问题并不提示错误
去掉lang也不行
希望看一下，谢谢~

**Comment by Hooper93** [comment]
发现问题了，如图，添加了src属性之后开始检查了，但这明显是错误的：
![Uploading image.png…]()
希望看一下是FECS的问题还是插件的问题，目前换了一种写法，直接把所有的js代码都单独拿出来了，但还是希望看一下该问题。

**Comment by l5oo00** [comment]
@Hooper93 图裂了， 能重新传一下不

**Comment by l5oo00** [comment]
我这试了下， v1.2.5 是可以的：

![image](https://user-images.githubusercontent.com/1233234/99479579-6c5d9080-2991-11eb-8aa3-82784dec0983.png)

你看看是不是装的最新版， 不过目前 Vue 的检测只有 script 部分是相对比较准的， template 部分是按 html 的规则检测的， 可能跟社区的规则有冲突， 会误报， 忽略即可~

**Comment by Hooper93** [comment]
我把fecs的插件去掉了，现在都走了 eslint 和stylelint 了~~
感觉fecs毛病有点多，参考资料也少得可怜 🥺

**Comment by Hooper93** [comment]
没啥问题了，我先关了哈~~ 感谢
