### ISSUE TITLE
Error: Cannot find module 'fecs'

### ISSUE THREAD

**Issue by laomu1024** [l5oo00/vscode-fecs-plugin#4]
在Mac的vscode 1.13.1版本中安装 vscode-fecs-plugin0.0.5版后使用时出现提示：

JS999: Error: Cannot find module '/Users/xxx/vscode-fecs-plugin/node_modules/fecs/lib/js/esnext'(    at Function.Module._resolveFilename (module.js). (rule: syntax)'
at: '470,15'

然后自己新建目录 /Users/YL07/Project/git_repo/ 并将工程克隆下来后就没这个错误提示了。。 可能是哪个地方引用或者配置有问题

**Comment by l5oo00** [comment]
应该是使用扩展自带的 fecs 模块导致的， 最新版已经改为使用全局安装的 fecs 模块了， 你更新试试。

**Comment by laomu1024** [comment]
更新后使用快捷键时提示，好像工具也不起作用了
![image](https://user-images.githubusercontent.com/6356903/27636080-5eca4ed4-5c3c-11e7-9f10-c75b2b4088a9.png)

command 'vscode-fecs-plugin.format' not found

![image](https://user-images.githubusercontent.com/6356903/27636006-ffafdca2-5c3b-11e7-9872-9b1996ecbe62.png)

**Comment by l5oo00** [comment]
2018.3.14： 最新版已经集成了1.5.5版本的 fecs， 不再依赖全局FECS 了。

--------

最新版使用了全局安装的 fecs， 并且不是使用的命令行， 而是直接在代码里 `const fecs = require('fecs');` , 所以请检查下面这几个点：

- 确保全局安装了  fecs (`fecs -v`)
- 确保环境变量里设置了 `NODE_PATH` 且指向了全局安装的 node 模块的目录
    > 全局目录可通过`npm root -g`命令获取， 如何设置 `NODE_PATH`请自行搜索

- 确保全局安装的 node 模块的目录里有 fecs 目录
    > 有人使用的 nvm 来管理 node 版本， 可能只在某一 node 版本内安装了 fecs , 切换版本后目录变化会导致找不到 fecs 模块，这时只需要切换回原版本， 或在新版本里重新按照 fecs 即可。
- 以上都确保没有问题后， 将此扩展更新到最新版， 重启 vscode即可。

---

下面附个 mac 下的 shell 代码， 可以直接 copy 到自己的`.bashrc`（或其他 shell 的配置文件， 比如`.zshrc`）文件里：
    
```shell
# 设置NODE_PATH环境变量
function setnodepath() {
    nodeglobelpath=`npm root -g`
    export NODE_PATH=$nodeglobelpath
}
setnodepath  # 使用 nvm 的用户， 请确保这个命令是在`nvm.sh`之后执行。
```

**Comment by jinzhubaofu** [comment]
@l5oo00 
根据 fecs 的这个 [PR](https://github.com/ecomfe/fecs/pull/290)，现在应该不会有  Cannot find module '/Users/xxx/vscode-fecs-plugin/node_modules/fecs/lib/js/esnext 这个问题了。

这个问题的原因是 fecs 在 postinstall 会去对自己的 node_modules/eslint 中的某个文件做修改，改成了一个系统绝对路径。如果插件安装时是在一个临时目录，这个绝对路径就是那个临时目录的路径。但是安装完成后被移动、临时目录不存在所以就出错了。

现在已经修掉了，建议把 fecs 改回到依赖试试看

**Comment by aFcFzF** [comment]
command 'vscode-fecs-plugin.format' not found   我也提示这个。。不知道该怎么做
fecs -v 是可以的。我的是win7 x64

**Comment by mcgradty** [comment]
@l5oo00 
我按照上面提示的方法去操作可是依然提示这个错误，是我的配置哪里出错了么
<img width="215" alt="qq20171002-005613 2x" src="https://user-images.githubusercontent.com/11990718/31056956-37ab4ed0-a6a0-11e7-87a9-376efd8f753a.png">
<img width="803" alt="qq20171002-005629 2x" src="https://user-images.githubusercontent.com/11990718/31056959-3fbfd05a-a6a0-11e7-87ee-d227f87c1774.png">

**Comment by l5oo00** [comment]
@aFcFzF @mcgradty 

首先，建议先用各种重启大法试试，还是有问题的话

建议你们在自己电脑上， 参考 fecs 官网的[api](http://fecs.baidu.com/api): `fecs.check` 和 `fecs.format` ， 以及官方的[测试用例](https://github.com/ecomfe/fecs/tree/master/test)

写个脚本试试， 先排查下是否是 fecs 配置的问题

还有问题， 就贴下具体的系统及环境等版本信息吧

**Comment by l5oo00** [comment]
@jinzhubaofu 又把 FECS 加入扩展依赖了， 不用再依赖全局的 FECS 了， 可以更新试试
