### ISSUE TITLE
不好使呀

### ISSUE THREAD

**Issue by maplebaby** [l5oo00/vscode-fecs-plugin#5]
不好使呀

**Comment by EcoRIIHC** [comment]
确实，第一次安装完有一个路径的warninig，然后在控制台里面是vscode自带的检查结果，我还以为是插件的输出，实际上并没有起作用。。

**Comment by l5oo00** [comment]
请参考这个试试   [Error: Cannot find module 'fecs'](https://github.com/l5oo00/vscode-fecs-plugin/issues/4#issuecomment-312411535)  #4
