### ISSUE TITLE
关于fecsrc的建议

### ISSUE THREAD

**Issue by laomu1024** [l5oo00/vscode-fecs-plugin#6]
1. 建议根据项目中配置的.fecsrc文件显示提示
2. 建议可配置为根据项目中是否存在.fecsrc来确定是否显示提示

**Comment by zoumiaojiang** [comment]
同样遇到这个问题，目前在项目里配置了 .fecsrc， 但是 .fecsrc 没生效

**Comment by l5oo00** [comment]
个人很少用 .fecsrc ， 所以没有考虑到这点，疏忽了。

后面我会抽空看看这块， 也欢迎大家提 pr。

**Comment by l5oo00** [comment]
插件已支持 `.fecsrc`, 各位可以更新试试。

唯一的缺点是， 每次更新了 `.fecsrc` 文件后需要 reload 下 vscode。
