### ISSUE TITLE
command 'vscode-fecs-plugin.format' not found

### ISSUE THREAD

**Issue by aFcFzF** [l5oo00/vscode-fecs-plugin#8]
大神，我的为啥不行呢。。
NODE_PATH 也对了。。
这里提示找不到
![baiduhi_2017-9-13_15-36-19](https://user-images.githubusercontent.com/19820728/30365191-88680602-9899-11e7-83ee-c5ed658adc62.png)

![baiduhi_2017-9-13_15-37-4](https://user-images.githubusercontent.com/19820728/30365204-8daef814-9899-11e7-89b7-36bef463d133.png)

**Comment by l5oo00** [comment]
是在运行 format 命令后报错的吗？

**Comment by l5oo00** [comment]
在这里 #4 讨论吧
