### ISSUE TITLE
windows下不好用

### ISSUE THREAD

**Issue by ghost** [l5oo00/vscode-fecs-plugin#9]
1、直接在终端执行fecs，检查是没有问题的。
![image](https://user-images.githubusercontent.com/10428816/39558700-6ba42632-4ec3-11e8-93fc-55395b178b53.png)

2、但是不管是FECS插件还是这个vscode-fecs-plugin插件，都检测不到错误。（已经禁用其他所有插件，排除干扰）
![image](https://user-images.githubusercontent.com/10428816/39558739-c4c1e0c4-4ec3-11e8-80cb-62e19338615f.png)

3、重启、重装都不好使。现在被迫使用笨重的webstrom，求大神排查解决~~

VS Code信息：
版本 1.22.2
提交 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
日期 2018-04-12T16:38:45.278Z
Shell 1.7.12
渲染器 58.0.3029.110
Node 7.9.0
架构 x64

fecs 版本：
$ fecs -v
fecs 1.5.5

系统：
win10-1706-专业版

**Comment by l5oo00** [comment]
看了下是 FECS check 失败。

目前的最新版本是将 FECS 直接打包到了插件内部， 我是在 Mac 下打包的， 可能 Win 下直接解压会有问题，可以进到 vscode 对应此插件的目录里， 将 node_modules 里的 FECS 删除， 然后直接在该目录`npm i fecs`， 完了重启 vscode 试试。

如果还不行， 着急的话， 建议你 `git clone`下来源码， 然后自己 debug 下看看，找出问题后欢迎提 pr。

或者等我周末看看。

**Comment by l5oo00** [comment]
问题已修复， 可以安装[最新版(0.1.2)](https://marketplace.visualstudio.com/items?itemName=l5oo00.vscode-fecs-plugin)试试。

看了下，问题可能是 FECS 的一个依赖库 [manis](https://github.com/ecomfe/manis) 在 Windows 下有兼容问题， 已提 [pr](https://github.com/ecomfe/manis/pull/6)。

因为此插件是将 FECS 直接打包进来， 所以我直接修改了我本地的 manis 依赖库， 重新打包后发布， 暂时不需要等官方修复。

但长远来看，还是需要依赖官方修复。
